name: seafile_server
services:
  db_seafile:
    container_name: seafile-mysql
    environment:
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_ROOT_PASSWORD=db_dev
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/seafile-mysql/db
        target: /var/lib/mysql
    networks:
      - db_seafile
    privileged: false
  memcached:
    container_name: seafile-memcached
    entrypoint:
      - memcached
      - -m
      - "256"
    image: memcached:1.6.18
    restart: unless-stopped
    networks:
      - db_seafile
    privileged: false
  seafile:
    container_name: seafile
    depends_on:
      db_seafile:
        condition: service_started
        required: true
      memcached:
        condition: service_started
        required: true
    environment:
      - DB_HOST=db_seafile
      - DB_ROOT_PASSWD=db_dev
      - SEAFILE_ADMIN_EMAIL=me@example.com
      - SEAFILE_ADMIN_PASSWORD=asecret
      - SEAFILE_SERVER_HOSTNAME=127.0.0.1:8022
      - SEAFILE_SERVER_LETSENCRYPT=false
      - TIME_ZONE=Europe/Madrid
    image: seafileltd/seafile-mc:latest
    ports:
      - target: 80
        published: "8022"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Seafile/opt/seafile-data
        target: /shared
    networks:
      - db_seafile
    privileged: false
networks:
  db_seafile:
    name: db_seafile
x-casaos:
  author: Labarta
  category: File Sync
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/seafile.png
  index: /
  port_map: "8022"
  scheme: http
  store_app_id: seafile_server
  title:
    custom: Seafile
  description:
    en_us: Seafile is an open-source, cross-platform file-hosting software system.
  tagline:
    en_us: Seafile is an open-source file sync and share solution designed for high reliability, performance, and productivity. 
  architectures:
    - amd64
    - arm64

